Description: Deploy ACM Certificate with DNS Validation

Resources:

  # IAM Role for the Lambda Function
  CustomACMLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies: # This is a list of policy documents
        - PolicyName: LambdaACMRoute53AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - acm:RequestCertificate
                  - acm:DescribeCertificate
                  - acm:DeleteCertificate
                  - acm:ListCertificates
                  - route53:ChangeResourceRecordSets
                Resource: "*"
        - PolicyName: LambdaS3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                # For all new projects, I'll need to add in their ARN here
                Resource:
                  - "arn:aws:s3:::salsa-tracker/*"

        - PolicyName: LambdaCloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
      Tags:
        - Key: Project
          Value: jiwanheo.xyz

      
  # Lambda Function to Handle ACM Validation
  CustomACMLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: create-and-validate-acm-ssl.lambda_handler
      Runtime: python3.13
      Code:
        S3Bucket: useful-functions
        S3Key: create-and-validate-acm-ssl.zip
      Timeout: 300
      Role: !GetAtt CustomACMLambdaExecutionRole.Arn
      Tags:
        - Key: Project
          Value: jiwanheo.xyz


  # Custom ACM Certificate Resource
  MyACMCertificate:
    Type: "Custom::ACM"
    Properties:
      ServiceToken: !GetAtt CustomACMLambdaFunction.Arn
      DomainName: "*.jiwanheo.xyz"
      HostedZoneId: Z066358329E65RHIEOJXQ
      Region: us-east-1
      Tags:
        - Key: Project
          Value: jiwanheo.xyz