name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main # Triggers on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Deploy stack
      - name: Deploy SSL Certificate Stack
        run: |
          aws cloudformation deploy \
            --template-file sslcert.yml \
            --stack-name jiwanheoXyz-SSLCertificateStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --tags Project=jiwanheo.xyz